# Generated by Django 5.0.6 on 2024-09-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='available_pin',
        ),
        migrations.RemoveField(
            model_name='board',
            name='numero',
        ),
    ]
