# Generated by Django 5.0.6 on 2024-09-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0002_remove_board_available_pin_remove_board_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
