# Generated by Django 5.0.6 on 2024-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0003_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='gpio',
            field=models.IntegerField(choices=[(1, '12'), (2, '16'), (3, '22'), (4, '28'), (5, '34')], null=True),
        ),
    ]
