# Generated by Django 5.0.6 on 2024-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0006_pins_consom_max_pins_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='last_off',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='last_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='consom_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pins',
            name='power',
            field=models.FloatField(),
        ),
    ]
