# Generated by Django 5.0.6 on 2024-09-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0007_messageboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='users',
        ),
    ]
