# Generated by Django 5.0.6 on 2024-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0007_pins_last_off_pins_last_on_alter_pins_consom_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='control_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pins',
            name='consom_max',
            field=models.FloatField(default=1000000000.0),
        ),
    ]
