# Generated by Django 5.0.6 on 2024-09-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0008_pins_control_mode_alter_pins_consom_max'),
        ('gpio', '0009_messageboard_tel_num'),
    ]

    operations = [
    ]
