# Generated by Django 5.0.6 on 2024-09-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0010_merge_20240914_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='today_limit_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pins',
            name='consom_max',
            field=models.FloatField(default=100000000000.0),
        ),
    ]
