# Generated by Django 5.0.6 on 2024-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='messages',
            name='user_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
