# Generated by Django 5.0.6 on 2024-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_messages_updated_at_messages_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='update_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
