# Generated by Django 5.0.6 on 2024-09-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_favorites_number_alter_favorites_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='number',
        ),
    ]
