# Generated by Django 5.0.6 on 2024-09-11 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_favorites_number'),
        ('gpio', '0005_remove_pins_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_code',
        ),
        migrations.AddField(
            model_name='messages',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_messages', to='gpio.board'),
        ),
        migrations.AddField(
            model_name='messages',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
