# Generated by Django 5.0.6 on 2024-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_messages_sent_remove_messages_user_code_and_more'),
        ('gpio', '0006_board_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='users_boards', to='gpio.board'),
        ),
    ]
