# Generated by Django 5.0.6 on 2024-09-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_boards'),
        ('gpio', '0007_messageboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient',
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_messages', to='gpio.messageboard'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
