# Generated by Django 5.0.6 on 2024-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_messages_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='out',
            field=models.BooleanField(default=True),
        ),
    ]
