# Generated by Django 5.0.6 on 2024-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_messages_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
