# Generated by Django 5.0.6 on 2024-09-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpio', '0007_pins_last_off_pins_last_on_alter_pins_consom_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temps', models.DurationField()),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpio.pins')),
            ],
        ),
    ]
